# There's no @sha256 for Renovate to trigger rebuild whenever the parent
# digest changes because we don't use anything from the parent image.
FROM registry.redhat.io/ubi9/ubi-init:9.5 AS builder

RUN mkdir -p /mnt/rootfs

#COPY ubi.repo /etc/yum.repos.d/ubi.repo

# Install redhat-release and import the GPG key. We can then later install more packages and verify the signatures
RUN \
    dnf install --installroot /mnt/rootfs \
        redhat-release \
        --releasever 9 --setopt install_weak_deps=false --nodocs --nogpgcheck -y && \
    rpm --root=/mnt/rootfs --import /mnt/rootfs/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

RUN \
    dnf install --installroot /mnt/rootfs --setopt=reposdir=/etc/yum.repos.d/ \
        bash \
        coreutils-single \
        crypto-policies-scripts \
        curl-minimal \
        libdnf-plugin-subscription-manager \
        findutils \
        gdb-gdbserver \
        glibc-minimal-langpack \
        gzip \
        langpacks-en \
        libcurl-minimal \
        rootfiles \
        subscription-manager \
        tar \
        vim-minimal \
        yum \
        --releasever 9 --setopt install_weak_deps=false --nodocs -y && \
    dnf --installroot /mnt/rootfs -y remove policycoreutils diffutils libselinux-utils

# Install Apache httpd and PHP
ARG INSTALL_PKGS="git rsync httpd php php-fpm php-mysqlnd php-pgsql php-bcmath php-gd php-intl php-ldap php-mbstring php-pdo php-process php-soap php-opcache php-xml php-gmp php-pecl-apcu php-pecl-zip mod_ssl hostname sqlite"

RUN dnf install --installroot /mnt/rootfs --setopt=reposdir=/etc/yum.repos.d/ -y --setopt=tsflags=nodocs $INSTALL_PKGS

COPY publichtml /mnt/rootfs/var/www/html/
RUN mv /mnt/rootfs/etc/httpd/conf.d/ssl.conf /mnt/rootfs/etc/httpd/conf.d/ssl.conf.disabled
RUN sed 's/Listen 80/Listen 8088/' -i /mnt/rootfs/etc/httpd/conf/httpd.conf
RUN cat /mnt/rootfs/usr/lib/systemd/system/httpd.service >/mnt/rootfs/etc/systemd/system/httpd.service
RUN sed 's/PrivateTmp=true/PrivateTmp=false/' -i /mnt/rootfs/etc/systemd/system/httpd.service

COPY apache/httpd/conf/httpd.conf /mnt/rootfs/etc/httpd/conf/httpd.conf
EXPOSE 8088

#EXPOSE 8443

# Copy the S2I scripts from the specific language image to $STI_SCRIPTS_PATH
#COPY ./s2i/bin/ $STI_SCRIPTS_PATH

# Copy extra files to the image.
#COPY ./root/ /

# Reset permissions of filesystem to default values
#RUN /usr/libexec/container-setup && rpm-file-permissions

# RPM uses a wrong file in the config
# Related: https://bugzilla.redhat.com/show_bug.cgi?id=2092356
#RUN sed -i "s/mod_php7.c/mod_php.c/" /etc/httpd/conf.d/php.conf

#USER 1001


RUN rm -rf /mnt/rootfs/var/cache/* /mnt/rootfs/var/log/dnf* /mnt/rootfs/var/log/yum.* /mnt/rootfs/var/lib/dnf/*

# Setup support for subscription-manager secrets
RUN cd /mnt/rootfs/etc && rm -rf ./pki/entitlement-host && ln -sf /run/secrets/etc-pki-entitlement ./pki/entitlement-host && \
    ln -sf /run/secrets/rhsm ./rhsm-host
RUN rm -f /mnt/rootfs/etc/systemd/system/multi-user.target.wants/rhsmcertd.service

# Set install langs macro so that new rpms that get installed will
# only install langs that we limit it to.
RUN echo "%_install_langs C.utf8" > /mnt/rootfs/etc/rpm/macros.image-language-conf && \
    echo "LANG=C.utf8" > /mnt/rootfs/etc/locale.conf

# Double check this is needed
RUN rm -f /mnt/rootfs/etc/sysconfig/network-scripts/ifcfg-*

# Remove machine-id on pre generated images
RUN rm -f /mnt/rootfs/etc/machine-id && touch /mnt/rootfs/etc/machine-id && chmod 0444 /mnt/rootfs/etc/machine-id

# Remove the installed redhat.repo file
RUN rm -f /mnt/rootfs/etc/yum.repos.d/redhat.repo

# Manually mask off the systemd units and service so we don't get a login prompt
RUN cd /mnt/rootfs/etc/systemd/system/ && ln -s /dev/null systemd-logind.service && \
    ln -s /dev/null getty.target && ln -s /dev/null console-getty.service && \
    ln -s /dev/null sys-fs-fuse-connections.mount && ln -s /dev/null systemd-remount-fs.service && \
    ln -s /dev/null dev-hugepages.mount

# Create the /run/lock file
RUN install -d /mnt/rootfs/run/lock -m 0755 -o root -g root

FROM scratch
LABEL maintainer="Red Hat, Inc." \
      vendor="Red Hat, Inc."
LABEL url="https://www.redhat.com"
LABEL com.redhat.component="ubi9-container" \
      name="ubi9" \
      version="9.5" \
      distribution-scope="public"

#label for EULA
LABEL com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI"

#labels for container catalog
LABEL summary="Provides the latest release of Red Hat Universal Base Image 9."
LABEL description="The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly."
LABEL io.k8s.description="The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly."
LABEL io.k8s.display-name="Red Hat Universal Base Image 9"
LABEL io.openshift.expose-services=""
LABEL io.openshift.tags="base rhel9"

ENV container oci


COPY --from=builder /mnt/rootfs/ /
COPY --from=builder /etc/yum.repos.d/ubi.repo /etc/yum.repos.d/.

#RUN systemctl daemon-reload
RUN systemctl enable php-fpm
RUN systemctl enable httpd

#create a volume to store the sqlite database
RUN mkdir -p /sqlitedata
VOLUME /sqlitedata
RUN chown -R apache:apache /sqlitedata

#create a volume for httpd logs
#RUN rm -rfv /var/log/httpd
#RUN mkdir -v -p /var/log/httpd
#VOLUME /var/log/httpd
RUN chown -R apache:apache /var/www/html
#RUN chown -R apache:apache /var/log/httpd

#CMD ["/bin/bash"]
#CMD ["/usr/sbin/httpd", "-DFOREGROUND"]
CMD ["/usr/sbin/init"]
#CMD ["/usr/sbin/httpd", "-DFOREGROUND"]
